### PR TITLE
Add position on the left as player approaches A stairs from T spawn

### PR DESCRIPTION
**Pull request by ReneRebsdorf**
Adds the below position to the Water to B practice.

image

### CODE REVIEW

**Comment by ReneRebsdorf** [comment]
Hi @lengran 

I am a new user of this repository, and I really appreciate that you have taken the time to create this plugin :-)
I would like to contribute with more positions across maps, so I made this tiny PR to see if I got it right, please advise if and how you wish for me to contribute, and in what size PRs you prefer.

**Comment by lengran** [comment]
First of all, thanks for your contribution!
Though after reading the file attached to this PR, I found the position is added in the wrong position. It's my fault that didn't mention this in the README.md, that the order of bot spawning follows the order of positions given in the corresponding description files. So this line should be added at the beginning of the file so the bot will spawn ahead of other bots. Also an instance of spawn info should use a separate line. 
But anyway I can manually add this spawn to the practice template. So this should be fine. Again, thanks for you passion for this project!

**Comment by lengran** [comment]
The position you provided and the corner on the other side has been added.

**Comment by ReneRebsdorf** [comment]
@lengran could you elaborate what you mean with "Also an instance of spawn info should use a separate line"? :-)

By the way, does the txt file support comments, or maybe convert to a format which can, such as .yaml?
I am thinking it would be beneficial to describe where these positions are, as they are not so human-readable.

I can make a feature request based on this?

**Comment by ReneRebsdorf** [comment]
@lengran never mind, I get it now!
I had mistakenly ran the python script and outputted to the .txt file
But I had forgotten to add a newline before hand.

I will make a PR with more positions now that the method is known, and improve the instructions in the README. :-)

**Comment by lengran** [comment]
> @lengran could you elaborate what you mean with "Also an instance of spawn info should use a separate line"? :-)
> 
> By the way, does the txt file support comments, or maybe convert to a format which can, such as .yaml? I am thinking it would be beneficial to describe where these positions are, as they are not so human-readable.
> 
> I can make a feature request based on this?

Support of comments is implemented with [the latest commit](https://github.com/lengran/OpenPrefirePrac/commit/4732d9e22e966d9e3e227928ac2d65a0a0f9e32e). Comments attached at the end of each line of bot spawn positions are now safely ignored when loading into plugins.

As for fancy formats like .yaml or .json, they are not so friendly to counter strike players who don't have a programming background, so I don't really want to use them here. I want to leave as much possibility for players to customize their own practice profiles as possible.

**Comment by ReneRebsdorf** [comment]
Awesome! I agree and will include comments going forward

**Pull request closed without merging**
